### PR TITLE
Changing purejavacomm source to avoid insecure http repo

### PR DESCRIPTION
**Pull request by WhittlesJr**
Potential fix for issue https://github.com/peterschwarz/clj-serial/issues/9

### CODE REVIEW

**Comment by WhittlesJr** [comment]
I'm not sure about that travis failure... says it can't find "lein2."

**Comment by WhittlesJr** [comment]
Hmm, well looks like  Java 1.7.0_151 OpenJDK doesn't play nice with the github version of purejavacomm. This PR probably isn't going to work out so I'll close it and leave the issue to you.

**Comment by WhittlesJr** [comment]
Trying 1.0.2

**Comment by WhittlesJr** [comment]
Still not working with openjdk7...

**Comment by WhittlesJr** [comment]
It's simply a version incompatibility... purejavacomm needs Java 8 (which maps to major version 52 according to http://javarevisited.blogspot.com/2015/05/fixing-unsupported-majorminor-version.html). 

I think I know the answer, but is java 1.7 support mandatory?

**Comment by WickedShell** [comment]
This (the Java 8 issue) is something I struggled with in #7 as well. Changing to 1.0.1 is actually how we worked around it at the time, as 1.0.0 was released for Java 8 only.

Regarding openjdk6 comment if you look at the travis run it didn't swap to jdk6 it was still running 1.8.0_151

**Comment by peterschwarz** [comment]
Is there a way to use lein profiles for the various jdks?

**Comment by WickedShell** [comment]
@peterschwarz I don't know of one, it appears that OpenJDK 6 was removed from the trusty image and needs to be specifically installed now. https://github.com/travis-ci/travis-ci/issues/8199#issuecomment-327246053

**Comment by peterschwarz** [comment]
Shame that the developer didn't use maven classifiers for that.  Will do some research.

**Comment by peterschwarz** [comment]
Could probably update the travis.yaml with the correct set of JDK options in a separate PR

**Comment by WickedShell** [comment]
I just sent one in to try that for JDK6, I should have just enabled travis on my clone rather then PR'ing it first... (Sorry)

**Comment by peterschwarz** [comment]
Going to merge in #11 and then you can see if that fixes this issue.  If so, I will close this PR and the corresponding issue.

**Comment by peterschwarz** [comment]
The issue seems to be resolve, so I will close this PR

**Pull request closed without merging**
