### PR TITLE
Add OpenJDK6 to travis deps

### PR DESCRIPTION
**Pull request by WickedShell**
Attempting to fix the OpenJDK6 error in #10

EDIT: I really should just enable Travis on my fork rather then using PR's to do Travis runs.

### CODE REVIEW

**Comment by peterschwarz** [comment]
It looks like Travis has changed how lein projects have to be specified (it has been a long time since this was setup).  `lein2` is now just `lein` and the old version is now `lein1`.  If you could update this PR with that change, that would be cool

**Comment by peterschwarz** [comment]
See https://docs.travis-ci.com/user/languages/clojure/

**Comment by WickedShell** [comment]
Will do, unfortunately its still running the jdk switcher before install apt packages, so I need to force the package to happen first.

**Comment by WickedShell** [comment]
Fixed lein, but that brings me back to the error that #10 was attempting to fix...

**Comment by WickedShell** [comment]
Okay this approach to Travis works, although it's a bit messy. Rather then running each task as a it's own build job this runs them all in one job (which given how fast it is to run it I think is quite reasonable). Definitely don't merge it with the commit to project.clj, that was just a work around to see travis pass. 

This unfortunately breaks on major/minor versions again, and oraclejdk isn't default installed either anymore... Realistically we should probably be testing JDK8 and JDK9 these days. I'll probably look at adding the OpenJDK versions. With that done though is there a preference for which OracleJDK is tested? If we are willing to move from OracleJDK7 to OracleJDK8 it's provided in the trusty image for us already and is easy.

**Comment by WickedShell** [comment]
If we drop Java6 support this is all very easy. Unfortunately all the recent build of PureJavaComm don't support Java6, and they have even updated some old released versions at some point. (I used to have an older machine that could grab an appropriate old jar file, but I deleted my maven cache one day and the resource I wanted had been replaced with a newer JVM requirement)

**Comment by peterschwarz** [comment]
I'm actually fine with dropping JDK6 support.

**Comment by WickedShell** [comment]
We'd have to drop Java7 as well and that's a bit more painful... (I hadn't read far enough down). I don't need Java7 personally, but thats much more likely to still be in deployment somewhere. (Effectively we have already dropped support for Java7 because if you grab the resources today it won't work).

Given that a new clone doesn't work with Java 6 or Java 7 at this point until they release a version that adds support back in, I suggest just dropping it from the test env since it's already broken outside of us.

**Comment by WickedShell** [comment]
Alright if everyone is happy with only testing Java 8 and 9 this resolves the CI problems, closes #9 and #10

**Pull request merged**
